### ISSUE TITLE
Script overrides normal shell color

### ISSUE THREAD

**Issue by brianjohnsen** [mathifonseca/grails-version-update#2]
The lines:
101 and 107 dictates the color og the shell after the script has run.
This is annoying if one doesn't use af black theme.

**Comment by mathifonseca** [comment]
This is very true. My fault for assuming that everyone uses a black background. I could make it optional in the configuration and let you deactivate it, what do you think?

**Comment by brianjohnsen** [comment]
Thanks for your quick response!
Optional deactivation would work just fine.

/brian
Den 31/08/2015 3.14 PM skrev "Mathi Fonseca" <notifications@github.com>:

**Comment by mathifonseca** [comment]
Hi @brianjohnsen, sorry for my delay. I've just released a new version 1.4.0 with the possibility to deactivate colored output. Please read the README.md file in this repository for information on how to set it.

**Comment by brianjohnsen** [comment]
Beautiful! Thanks for your quick response!
