### ISSUE TITLE
Create SNAPSHOT versions

### ISSUE THREAD

**Issue by mariodavid** [mathifonseca/grails-version-update#3]
Hi,

would it be possible to extend the plugin in the form, that it is possible to update to a "-SNAPSHOT" version?

As an example usage i would think of something like: "grails version-update p s" which turns 1.2.5 to 1.2.6-SNAPSHOT and "grails version-update m s" which turns 1.2.6 to 1.3.0-SNAPHOST accordingly.

thx

**Comment by mathifonseca** [comment]
Excellent proposal! I'll add it asap and let you know.

**Comment by mathifonseca** [comment]
OK, I was in a great mood and made that change really quickly :smiley:. Please try version 1.5.0 and let me know if that's what you were looking for. I also updated the documentation to explain your idea.

**Comment by mariodavid** [comment]
hi,

that was a really quick fix :) thanks, it works great.

bye
