### ISSUE TITLE
What if I need w.x.y.z format ?

### ISSUE THREAD

**Issue by wureka** [mathifonseca/grails-version-update#6]
I am using Grails 3.1.10
If my version format is w.x.y.z, the command grails version-update will appears below error:
Error Current version does NOT comply with expectations!

Based on your document, the block versionUpdate {...} is located in BuildConfig.groovy in Grails 2.x
As for Grails 3.x, in which file should I put versionUpdate {...} ?

Thanks

**Comment by mathifonseca** [comment]
Hi @wureka! I'm sorry it took me so long to reply. The version I ported to Grails 3.x doesn't have all the configuration options that the previous one had. As I was not using Grails 3.x, I had trouble migrating that part and let it out, at least for the first version. Please feel free to add it and send a PR, I'll publish a new version asap.
